apiVersion: v1
kind: Service
metadata:
  name: service-internal-mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: service-internal-mysql
      port: 9000
      targetPort: 3306