version: "3"

services:
  mysql:
    container_name: local_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci